baseURL = "/"
languageCode = "en-us"
title = "990 Consulting"

[Params]
twitter = "https://twitter.com"
linkedin = "https://linkedin.com"
facebook = "https://facebook.com"

date_format = "Jan 2, 2006"

[taxonomies]
  tag = "tags"
